add contact avatar feature
EinfachHans/cordova-plugin-contacts-x pull request #14
Opened 2021-07-07 03:31 UTC by SpeakSugar

2021-07-07 08:02 UTC, EinfachHans requested changes
- Add `avatar` to definition File
- Add it to Documentation with a Usage example
- If we add a feature to save a contact with an avatar, we should make sure to be able to edit the avatar of an existing contact as well
- If we add a Feature to save a contact with an avatar we also should have the feature to include the avatars in the find method

2021-07-07 08:02 UTC, EinfachHans commented on src/android/ContactsX.java
> +import java.util.*;
Why are you importing the whole **java.util** here?

2021-07-08 01:35 UTC, SpeakSugar commented on src/android/ContactsX.java
> +import java.util.*;
maybe I import base64 util, which caused the idea editor merge it to '*'. Does this affect performance?

2021-07-08 01:42 UTC, SpeakSugar commented
> * Add `avatar` to definition File
> * Add it to Documentation with a Usage example
> * If we add a feature to save a contact with an avatar, we should make sure to be able to edit the avatar of an existing contact as well
> * If we add a Feature to save a contact with an avatar we also should have the feature to include the avatars in the find method

If I have time, I will finish it later

2021-07-08 06:45 UTC, EinfachHans commented on src/android/ContactsX.java
> +import java.util.*;
I don't think so, i just don't like it. I think importing the single Classes gives a better overview

2021-07-08 06:48 UTC, SpeakSugar commented on src/android/ContactsX.java
> +import java.util.*;
ok, I will fix it and pull new request again

2024-01-29 12:14 UTC, closed without merging